# Python kræsjkurs dag 2

#### kl.17:15-19:00 22.01.2025

## Lister og tupler

In [ ]:
element_1 = 1
element_2 = False
element_3 = "Hei!"

In [ ]:
liste = [element_1, element_2, element_3]
liste

In [ ]:
tupel = (element_1, element_2, element_3)
tupel

### Indeksing

In [ ]:
liste[1]

In [ ]:
liste[2]

In [ ]:
tupel[1]

In [ ]:
tupel[0]

In [ ]:
liste[3]

In [ ]:
liste[2] = "Hade!"

In [ ]:
print(liste)

In [ ]:
tupel[2] = 'Hade!'

### Negativ indeksing

In [ ]:
liste

In [ ]:
liste[-1]

In [ ]:
liste[-2]

In [ ]:
liste[-3]

In [ ]:
liste[-4]

#### Oppgave

Lag en liten handleliste som inneholder: brød, melk og ost.

In [ ]:
handleliste = ["brød", "melk", "ost"]

## Løkker
Hvordan gjenta handlinger?
### For-løkker

#### Eksempel
Skriv ut tallene fra 1 til 100.

In [ ]:
for tall in range(1, 101):
    print(tall)

#### Eksempel 
Skriv ut elementene i følgende handleliste.

In [ ]:
handleliste = ["Melk", "Ost", "9 Epler", "Pære"]

In [ ]:
for mat in handleliste:
    print(mat)

#### Skriv ut alle tallene som er større enn 25

In [ ]:
mange_tall = [-1, 100, 30, 80, 10, 2, -100, 40, 70]
over_25 = []

In [ ]:
for tall in mange_tall:
    if tall > 25:
        over_25.append(tall)

print(over_25)

#### Oppgave trinnskatt
Trinnskatt beskrives her: https://www.skatteetaten.no/satser/trinnskatt/.

a) Lag to lister med trinnskatt og grensene for trinnskatten.

b) Finn skatten til en person med inntekt på 10'000'000 NOK ved å bruke en for løkke.

In [ ]:
trinnskatt_prosent = [0, 1.7, 4, 13.7, 16.7, 17.7]
trinnskatt_nedre_grenser = [0, 217401, 306051, 697151, 942401, 1410751]

In [ ]:
inntekt = 10000000
skatt = 0
ikke_beskattet = inntekt

for trinn in range(6):
    if ikke_beskattet >= trinnskatt_nedre_grenser[-trinn-1]:
        skatt = skatt + (ikke_beskattet-trinnskatt_nedre_grenser[-trinn-1])*trinnskatt_prosent[-trinn-1]/100
        ikke_beskattet = trinnskatt_nedre_grenser[-trinn-1] - 1
        
        
print(skatt)

### While-løkker
Brukes når vi ikke vet hvor mange ganger den skal kjøres.

#### Eksempel 1
Se om feilen er over terskelverdien.

In [ ]:
feilledd = list(range(1, 100))
print(feilledd)

In [ ]:
indeks = 0

In [ ]:
terskelverdi = 25

while feilledd[indeks] < terskelverdi:
    print(feilledd[indeks])
    indeks += 1

#### Eksempel 2

Lag alle fibonacci tallene under 100.

https://en.wikipedia.org/wiki/Fibonacci_sequence

In [9]:
a_n = 0
a_n_1 = 1

In [10]:
while a_n_1 < 1200:
    a_n_2 = a_n_1 + a_n
    a_n = a_n_1
    a_n_1 = a_n_2
    
    print(a_n)

1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987


## Numpy

In [11]:
# Pakkeimport for mer funksjonalitet
import numpy as np

### Vektoroperasjoner

In [12]:
vektor_1 = np.array([1, 2, 3, 4])
vektor_1

array([1, 2, 3, 4])

In [13]:
vektor_2 = np.array([3, 2, 1, 0])
vektor_2

array([3, 2, 1, 0])

In [16]:
2 * vektor_1 + vektor_2

array([5, 6, 7, 8])

In [17]:
vektor_1 * vektor_2

array([3, 4, 3, 0])

### Vektorer
Andre måter å lage vektorer på.

In [26]:
# Vektor med 10 punkter i intervallet [1, 2]
np.linspace(1, 2, 10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [25]:
# Tallene fra 1 til 99
np.arange(1, 100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### Eksempel
Finn følgende kombinasjoner av vektorene 
- $\vec{v}_1 = (1, 2, 3, 4)$ og
- $\vec{v}_2 = (12, 11, 12, 0)$.

Finn $2\vec{v}_1-\vec{v}_2$.


In [28]:
v_1 = np.arange(1, 5)
v_1

array([1, 2, 3, 4])

In [29]:
v_2 = np.array([12, 11, 12, 0])

In [32]:
2*v_1 - v_2

array([-10,  -7,  -6,   8])

### Matriser

In [37]:
matrise = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
matrise

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
# Antall rader og kolonner
matrise.shape

(4, 3)

In [35]:
# Antall posisjoner
matrise.size

12

### Lineærkombinasjoner

In [38]:
matrise_1 = np.array([[1, 2, 3], [2, 0, 1]])
matrise_1

array([[1, 2, 3],
       [2, 0, 1]])

In [39]:
matrise_2 = np.array([[1, 0, 1], [1, 0, 1]])
matrise_2

array([[1, 0, 1],
       [1, 0, 1]])

In [40]:
2 * matrise_1

array([[2, 4, 6],
       [4, 0, 2]])

In [41]:
matrise_1 - matrise_2

array([[0, 2, 2],
       [1, 0, 0]])

In [42]:
matrise_1 * matrise_2

array([[1, 0, 3],
       [2, 0, 1]])

### Matrisemultiplikasjon

In [43]:
A = np.array([[1, 0], [2, 3]])
B = np.array([[2, 0], [1, 1]])

Finn matrisemultiplikasjonen 
$$AB=\begin{bmatrix}1&0\\2&3\end{bmatrix}\begin{bmatrix}2&0\\1&1\end{bmatrix}.$$

In [44]:
A @ B

array([[2, 0],
       [7, 3]])

#### Finn matrisemultiplikasjonen 
$$A\begin{bmatrix}1\\2\end{bmatrix}=\begin{bmatrix}1&0\\2&3\end{bmatrix}\begin{bmatrix}1\\2\end{bmatrix}.$$

In [45]:
vektor = np.array([1, 2])

In [47]:
A @ vektor

array([1, 8])

### Transponere matriser

In [48]:
A

array([[1, 0],
       [2, 3]])

In [49]:
A.T

array([[1, 2],
       [0, 3]])

In [50]:
matrise_1

array([[1, 2, 3],
       [2, 0, 1]])

In [51]:
matrise_1.T

array([[1, 2],
       [2, 0],
       [3, 1]])